#!/bin/bash
# vim: set ft=bash syntax=on

alias rpm-keys="rpm -q gpg-pubkey --qf '%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n'"

function kto {
  gdb --batch-silent --pid=$$ --eval-command='call unbind_variable("TMOUT")'
}

function td {
  sudo kill $(cat /var/run/openvpn.pid)
  sudo rm -f /var/run/openvpn.pid
}

function tu {
  if ip link | grep -qP '^\d: tun\d:'; then
    echo 'the tunnel is already up'
  else
    sudo openvpn --daemon vpn \
      --config $HOME/.openvpn/openvpn.config \
      --writepid /var/run/openvpn.pid
  fi
}
