#!/bin/bash

# usage:
#
# cert-make 'C=GB,L=Cardiff,CN=foo.mac.wales'
#
# defaults to CN=$HOSTNAME
#

if [ -z "$1" ]; then
  DN="CN=$HOSTNAME"
else
  DN="$1"
fi

SUBJECT=$(echo $DN | tr ',' '\n')
ATTRIBUTES=$(echo $DN | tr ',' ' ')

for A in $ATTRIBUTES; do
  eval "export DN_${A}"
done

CN="$DN_CN"

CONFIG="/tmp/${CN}.conf"
CERT="/tmp/${CN}.crt"
KEY="/tmp/${CN}.pem"

cat > "${CONFIG}" <<EOF
[req]
default_bits = 2048
prompt = no
default_md = sha256
distinguished_name = dn
x509_extensions = v3_req

[dn]
${SUBJECT}

[v3_req]
subjectAltName = @alt_names
basicConstraints = CA:FALSE

[alt_names]
DNS.1 = ${CN}
EOF

openssl req -x509 \
  -batch \
  -config "${CONFIG}" \
  -newkey rsa:4096 -nodes \
  -keyout "${KEY}" \
  -out "${CERT}" \
  -days 3650

openssl x509 -in "${CERT}" -text -noout

rm -f "${CONFIG}"

echo
echo $CERT
echo $KEY
