#!/bin/bash

# usage:
#
# cert-make <FDN> <DNS/IP SAN>*
#
# cert-make 'C=GB,ST=Wales,L=Cardiff,O=McGarrigle,CN=foo.mac.wales' 'DNS=www.mac.wales' 'DNS=*' 'IP=192.168.1.1' 'IP=192.168.1.2'
#
# defaults to CN=$HOSTNAME
#

lines() {
  tr ' ' '\n'
}

if [ -z "$1" ]; then
  DN="CN=$HOSTNAME"
else
  DN="$1"
fi
shift

SUBJECT=$(echo $DN | tr ',' '\n')
ATTRIBUTES=$(echo $DN | tr ',' ' ')

for A in $ATTRIBUTES; do
  eval "export DN_${A}"
done

CN="$DN_CN"

DNS=$(echo "DNS=${CN} $@" | lines | grep "DNS=" | awk -F'=' '{ print "DNS." NR "=" $2 }')
IPS=$(echo "$@" | lines | grep "IP=" | awk -F'=' '{ print "IP." NR "=" $2 }')

CONFIG="/tmp/${CN}.conf"
CERT="/tmp/${CN}.crt"
KEY="/tmp/${CN}.pem"

cat > "${CONFIG}" <<EOF
[req]
default_bits = 2048
prompt = no
default_md = sha256
distinguished_name = dn
x509_extensions = v3_req

[dn]
${SUBJECT}

[v3_req]
subjectAltName = @alt_names
basicConstraints = CA:TRUE

[alt_names]
${DNS}
${IPS}
EOF

openssl req -x509 \
  -config "${CONFIG}" \
  -newkey rsa:4096 \
  -nodes \
  -keyout "${KEY}" \
  -out "${CERT}" \
  -days 3650

openssl x509 -in "${CERT}" -text -noout

rm -f "${CONFIG}"

echo
echo $CERT
echo $KEY
