#!/bin/bash

SUBJECT="$1"
CONFIG="/tmp/${SUBJECT}.conf"

cat > "${CONFIG}" <<EOF
[req]
default_bits = 2048
prompt = no
default_md = sha256
distinguished_name = dn
x509_extensions = v3_req

[dn]
C = UK
ST = Wales
L = Cardiff
O = MAC.WALES
CN = ${SUBJECT}

[v3_req]
subjectAltName = @alt_names
basicConstraints = CA:TRUE

[alt_names]
DNS.1 = ${SUBJECT}
EOF

CERT="/etc/pki/tls/certs/${SUBJECT}.crt"
KEY="/etc/pki/tls/private/${SUBJECT}.pem"

openssl req -x509 \
  -config "${CONFIG}" \
  -newkey rsa:4096 -nodes \
  -keyout "${KEY}" \
  -out "${CERT}" \
  -days 3650

openssl x509 -in "${CERT}" -text -noout

rm -f "${CONFIG}"

echo
echo $CERT
echo $KEY
