#!/usr/bin/env python3

# mytube 'http://youtube.com/watch?v=9bZkp7q19f0'

import sys
from pytube import YouTube

url = sys.argv[1]
yt = YouTube(url)
yt.streams.filter(only_audio=True).desc().first().download()
