#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4

import re
import subprocess

class Interface:

    def __init__(self):
        self.name = None
        self.mac  = None

class NetworkLinks:

    def __init__(self):
        links = subprocess.check_output(['ip', '-o', 'link'])
        self.links = map(lambda s: self.to_interface(s), links.splitlines())

    def to_interface(self, s):
        print(s)
        r = re.match('\d+: (\w+).*link/\w+ ([0-9a-f:]+)', s)
        i = Interface()
        i.name = r.group(1)
        i.mac  = r.group(2)
        return i

l = NetworkLinks()
for i in l.links:
    print(i.name)
    print(i.mac)
