#!/usr/bin/env python

import sys
import random
import string
import crypt

plain = sys.argv[1]
alphabet = string.ascii_uppercase + string.ascii_lowercase + string.digits
salt = ''.join(random.choice(alphabet) for _ in range(16))
sha =  crypt.crypt(plain, '$6$%s$' % salt)

print(sha)
