# Options

# Use tmux-256color or screen-256color
set -g default-terminal "tmux-256color"

# Enable RGB/True Colour support
# Replace 'xterm-256color' with whatever your 'echo $TERM' outputs OUTSIDE of tmux
set -as terminal-features ',xterm-256color:RGB'
set -sg terminal-overrides ',xterm-256color:RGB'

set -g escape-time 0  # disable delays on escape sequences
set -g mouse on
set -g renumber-windows on  # keep numbering sequential
set -g repeat-time 1000  # increase "prefix-free" window

# Options: start indexes from 1
set -g base-index 1
set -g pane-base-index 1

# Change prefix
unbind C-b
set -g prefix §
bind § send-prefix

# Theme: borders
# set -g pane-border-lines simple
set -g pane-border-style fg=gray
set -g pane-active-border-style fg=yellow

# Theme: status
set -g status-position top
set -g status-style bg=default,fg=gray
set -g status-left ""
set -g status-right "#[fg=blue,bright]%H:%M:%S"

# Theme: status (windows)
set -g window-status-format " #{window_index}:#{window_name}"
set -g window-status-current-format " #{window_index}:#{window_name}"
set -g window-status-current-style "fg=yellow,bright"
set -g window-status-bell-style "fg=red,nobold"

# Keybindings: disable repeat for arrows
bind Up select-pane -U
bind Left select-pane -L
bind Down select-pane -D
bind Right select-pane -R

# Keybindings: split
bind h split-window -h
bind | split-window -h
bind v split-window -v
bind - split-window -v

# Keybindings: windows
bind -n C-Tab next-window
bind -n C-S-Tab previous-window

# Keybindings: other
bind f resize-pane -Z
bind q detach-client
bind e choose-window -Z
