#!/usr/bin/env python3

import subprocess
import re
import argparse

def command(*cmd):
   s = subprocess.check_output(cmd)
   return s.decode('utf-8')

def select(s, r):
  m = re.search(r, s)
  if m:
      return m.group(1)
  else:
      return None

def vmlist(mode):
    s = command('vboxmanage', 'list', mode)
    vms = [select(x, '"(.*)"') for x in s.splitlines()]
    return vms

def list_command():
    rvm = vmlist('runningvms')
    for vm in vmlist('vms'):
        if vm in rvm:
            print('r', vm)
        else:
            print('-', vm)

parser = argparse.ArgumentParser()
subparsers = parser.add_subparsers(dest='command', help="help")
list_parser = subparsers.add_parser('list', help='list help')
list_parser.add_argument("-v", "--verbose", help="more info", action="store_true")
info_parser = subparsers.add_parser('info', help='info help')
args = parser.parse_args()

if args.command == 'list':
    list_command()
