#!/bin/bash

function configure_local {
  hostnamectl set-hostname "$1.local"
  yum install -y epel-release
  yum install -y nss-mdns avahi avahi-tools bind-utils
  systemctl enable avahi-daemon.service --now
  systemctl restart avahi-daemon.service
  systemctl enable firewalld --now
  firewall-cmd --permanent --add-service=mdns  # permanent
}

function configure_shell {
  echo -e '\n. $HOME/bin/bashrc\n' >> ~/.bashrc
  ln -s bin/vimrc     .vimrc
  ln -s bin/tmux.conf .tmux.conf
}

function configure_docker {
  yum install -y yum-utils
  yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  yum install -y docker-ce docker-ce-cli containerd.io
  systemctl enable docker --now
  curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  chmod +x /usr/local/bin/docker-compose
}

function configure_vim {
  git clone git@github.com:tpope/vim-pathogen.git ~/.vim
  mkdir ~/.vim/bundle
  git clone git@github.com:vim-airline/vim-airline.git ~/.vim/bundle/airline
  echo "execute pathogen#infect()" >> ~/bin/vimrc
}

function configure_help {
 echo "this is help"
}

cmd="configure_$1"
shift

$cmd $@

