#!/bin/bash

function configure_local {
  hostnamectl set-hostname "$1.local"
  yum install -y epel-release
  yum install -y nss-mdns avahi avahi-tools bind-utils
  systemctl enable avahi-daemon.service --now
  systemctl restart avahi-daemon.service
  systemctl enable firewalld --now
  firewall-cmd --permanent --add-service=mdns  # permanent
}

function configure_shell {
  echo -e '\n. $HOME/bin/bashrc\n' >> ~/.bashrc
  ln -s bin/vimrc     .vimrc
  ln -s bin/tmux.conf .tmux.conf
}

function configure_help {
 echo "this is help"
}

cmd="configure_$1"

$cmd

