#!/bin/bash

function conf_local {
  hostnamectl set-hostname "$1.local"
  yum install -y epel-release
  yum install -y nss-mdns avahi avahi-tools bind-utils
  systemctl enable avahi-daemon.service --now
  systemctl restart avahi-daemon.service
  systemctl enable firewalld --now
  firewall-cmd --permanent --add-service=mdns  # permanent
}

function conf_help {
 echo "this is help"
}

cmd="conf_$1"

$cmd

