#!/bin/sh

function nodes {
  docker node ls -q | xargs docker node inspect 
}

function json {
  nodes | jq 'map({"node":.Description.Hostname, "labels" : .Spec.Labels})'
}

function command_json {
  json
}

function command_list {
  json | jq -r 'map("\(.node): " + (.labels | to_entries | map("\(.key)=\(.value)") | join(" "))) | .[]'
}

function command_select {
  json | jq "map(select(.labels.$1))"
}

function command_help {
  echo "docker-labels"
  echo "  --list"
  echo "  --json"
  echo "  --select <label>"
}

if [ -z "$1" ]; then
  if [ -t 1 ]; then
    command_list
  else
    command_json
  fi
else
  FN="${1/--/command_}"
  shift 
  ${FN} $@
fi
