#!/usr/bin/env python3

import os
import configparser

home = os.environ["HOME"]
config = configparser.ConfigParser()
config.read(f"{home}/.gitconfig")

print(f"git config --global user.name '{config.get('user', 'name')}'")
print(f"git config --global user.email '{config.get('user', 'email')}'")
print(f"git config --global push.default current")
