# bash/zsh git prompt support
# #
# # Copyright (C) 2006,2007 Shawn O. Pearce <spearce@spearce.org>
# # Distributed under the GNU General Public License, version 2.0.
# #
# # This script allows you to see repository status in your prompt.
# #
# # To enable:
# #
# #    1) Copy this file to somewhere (e.g. ~/.git-prompt.sh).
# #    2) Add the following line to your .bashrc/.zshrc/.profile:
# #        . ~/.git-prompt.sh   # dot path/to/this-file
# #    3a) Change your PS1 to call __git_ps1 as
# #        command-substitution:
# #        Bash: PS1='[\u@\h \W$(__git_ps1 " (%s)")]\$ '
# #        ZSH:  setopt PROMPT_SUBST ; PS1='[%n@%m %c$(__git_ps1 " (%s)")]\$ '
# #        the optional argument will be used as format string.
# #    3b) Alternatively, for a slightly faster prompt, __git_ps1 can
# #        be used for PROMPT_COMMAND in Bash or for precmd() in Zsh
# #        with two parameters, <pre> and <post>, which are strings
# #        you would put in $PS1 before and after the status string
# #        generated by the git-prompt machinery.  e.g.
# #        Bash: PROMPT_COMMAND='__git_ps1 "\u@\h:\w" "\\\$ "'
# #          will show username, at-sign, host, colon, cwd, then
# #          various status string, followed by dollar and SP, as
# #          your prompt.
# #        ZSH:  precmd () { __git_ps1 "%n" ":%~$ " "|%s" }
# #          will show username, pipe, then various status string,
# #          followed by colon, cwd, dollar and SP, as your prompt.
# #        Optionally, you can supply a third argument with a printf
# #        format string to finetune the output of the branch status
# #
# #    See notes below about compatibility with other shells.
# #
# # The repository status will be displayed only if you are currently in a
# # git repository. The %s token is the placeholder for the shown status.
# #
# # The prompt status always includes the current branch name.
# #
# # In addition, if you set GIT_PS1_SHOWDIRTYSTATE to a nonempty value,
# # unstaged (*) and staged (+) changes will be shown next to the branch
# # name.  You can configure this per-repository with the
# # bash.showDirtyState variable, which defaults to true once
# # GIT_PS1_SHOWDIRTYSTATE is enabled.
# #
# # You can also see if currently something is stashed, by setting
# # GIT_PS1_SHOWSTASHSTATE to a nonempty value. If something is stashed,
# # then a '$' will be shown next to the branch name.
# #
# # If you would like to see if there're untracked files, then you can set
# # GIT_PS1_SHOWUNTRACKEDFILES to a nonempty value. If there're untracked
# # files, then a '%' will be shown next to the branch name.  You can
# # configure this per-repository with the bash.showUntrackedFiles
# # variable, which defaults to true once GIT_PS1_SHOWUNTRACKEDFILES is
# # enabled.
# #
# # If you would like to see the difference between HEAD and its upstream,
# # set GIT_PS1_SHOWUPSTREAM="auto".  A "<" indicates you are behind, ">"
# # indicates you are ahead, "<>" indicates you have diverged and "="
# # indicates that there is no difference. You can further control
# # behaviour by setting GIT_PS1_SHOWUPSTREAM to a space-separated list
# # of values:
# #
# #     verbose       show number of commits ahead/behind (+/-) upstream
# #     name          if verbose, then also show the upstream abbrev name
# #     legacy        don't use the '--count' option available in recent
# #                   versions of git-rev-list
# #     git           always compare HEAD to @{upstream}
# #     svn           always compare HEAD to your SVN upstream
# #
# # By default, __git_ps1 will compare HEAD to your SVN upstream if it can
# # find one, or @{upstream} otherwise.  Once you have set
# # GIT_PS1_SHOWUPSTREAM, you can override it on a per-repository basis by
# # setting the bash.showUpstream config variable.
# #
# # You can change the separator between the branch name and the above
# # state symbols by setting GIT_PS1_STATESEPARATOR. The default separator
# # is SP.
# #
# # When there is an in-progress operation such as a merge, rebase,
# # revert, cherry-pick, or bisect, the prompt will include information
# # related to the operation, often in the form "|<OPERATION-NAME>".
# #
# # When the repository has a sparse-checkout, a notification of the form
